### ISSUE TITLE
cannot uninstall

### ISSUE THREAD

**Issue by mesqueeb** [importre/alfred-mdi#3]
I installed this package by mistake via `npm i -g alfred-mdi`
but now I can't uninstall it any more:

```

> alfred-mdi@0.2.1 preuninstall /usr/local/lib/node_modules/alfred-mdi
> alfy-cleanup

Error: Command failed: alfred-unlink
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module './'
Require stack:
- /usr/local/lib/node_modules/alfred-mdi/node_modules/.bin/alfred-unlink
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-mdi/node_modules/.bin/alfred-unlink:3:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/alfred-mdi/node_modules/.bin/alfred-unlink'
  ]
}


    at /usr/local/lib/node_modules/alfred-mdi/node_modules/execa/index.js:236:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'internal/modules/cjs/loader.js:797\n' +
    '    throw err;\n' +
    '    ^\n' +
    '\n' +
    "Error: Cannot find module './'\n" +
    'Require stack:\n' +
    '- /usr/local/lib/node_modules/alfred-mdi/node_modules/.bin/alfred-unlink\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:687:27)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:849:19)\n' +
    '    at require (internal/modules/cjs/helpers.js:74:18)\n' +
    '    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-mdi/node_modules/.bin/alfred-unlink:3:20)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:956:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:812:32)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:724:14)\n' +
    '    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {\n' +
    "  code: 'MODULE_NOT_FOUND',\n" +
    '  requireStack: [\n' +
    "    '/usr/local/lib/node_modules/alfred-mdi/node_modules/.bin/alfred-unlink'\n" +
    '  ]\n' +
    '}\n',
  failed: true,
  signal: null,
  cmd: 'alfred-unlink',
  timedOut: false
}
npm WARN lifecycle alfred-mdi@0.2.1~preuninstall: continuing anyway alfred-mdi@0.2.1 preuninstall: `alfy-cleanup`
npm WARN lifecycle Exit status 1
npm ERR! code EEXIST
npm ERR! path /usr/local/lib/node_modules/alfred-mdi/node_modules/.bin/alfy-cleanup
npm ERR! Refusing to delete /usr/local/lib/node_modules/alfred-mdi/node_modules/.bin/alfy-cleanup: is outside /usr/local/lib/node_modules/alfred-mdi/node_modules/alfy and not a link
npm ERR! File exists: /usr/local/lib/node_modules/alfred-mdi/node_modules/.bin/alfy-cleanup
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lucaban/.npm/_logs/2019-10-27T12_20_53_926Z-debug.log
```

**Comment by youtextme** [comment]
For Mac bootstrap/dotfiles: a solid free-first launcher path is `brew install --cask raycast` alongside (or instead of) Alfred Powerpack. Keep Spotlight/Alfred on ⌘Space if you want, map Raycast to ⌥Space, and only consider Pro after free features stick. Avoid paying twice for the same clipboard/hotkey jobs.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
